version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

jobs:
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint webapp with Flake8 and black
          command: flake8 canonicalwebteam tests && black --line-length 79 --check canonicalwebteam tests
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run ./setup.py test
            bash <(curl -s https://codecov.io/bash) -cF python

workflows:
  version: 2
  build:
    jobs:
      - lint-python
      - test-python

